<?php
require_once("classes/Database.php");
require_once("classes/Student.php");
require_once("classes/Parents.php");
require_once("classes/Branch.php");
require_once("classes/Enquiry.php");
require_once("classes/Functions.php");
require_once("classes/User.php");
require_once("classes/Session.php");
?>